[package]
name = "echo-bot"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A simple echo bot example for the Alloy framework"
publish = false

[dependencies]
alloy = { path = "../../crates/alloy", features = ["ws-server"] }
alloy-adapter-onebot = { path = "../../crates/alloy-adapters/onebot" }
alloy-plugin-storage = { path = "../../examples/storage" }
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
serde_json = "1.0.149"
time = { version = "0.3.47", features = ["local-offset", "macros"] }
tokio = { version = "1.52.0", features = ["fs", "rt-multi-thread", "signal"] }
tracing = "0.1.44"
