[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/USTC-XeF2/amira"
authors = ["XeF2 <contact@xef2.top>"]
license = "MIT"

[workspace]
members = [
    "crates/amira",
    "crates/amira-core",
    "crates/amira-framework",
    "crates/amira-macros",
    "crates/amira-runtime",
    "crates/amira-transport",
    "adapters/milky",
    "adapters/onebot",
    "examples/echo-bot",
    "examples/plugin-storage",
]
resolver = "2"

[workspace.dependencies]
amira-core = { version = "0.1.0", path = "crates/amira-core" }
amira-framework = { version = "0.1.0", path = "crates/amira-framework" }
amira-macros = { version = "0.1.0", path = "crates/amira-macros" }
amira-runtime = { version = "0.1.0", path = "crates/amira-runtime" }
amira-transport = { version = "0.1.0", path = "crates/amira-transport" }

async-trait = "0.1.89"
bytes = "1.11.1"
derive_more = "2.1.1"
futures = "0.3.32"
parking_lot = "0.12.5"
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = "1.52.1"
tracing = "0.1.44"

[profile.release]
strip = true
lto = true
codegen-units = 1
