[package]
name = "alloy-core"
version = { workspace = true }
description = "Core engine for the Alloy bot framework"
edition = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true, features = ["as_ref", "deref", "deref_mut", "from", "into", "into_iterator"] }
downcast-rs = "2.0.2"
futures = { workspace = true }
http = "1.4.0"
linkme = "0.3.35"
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
